# Docker Compose configuration for DollhouseMCP
# Note: version field is obsolete and removed per Docker Compose v2

services:
  dollhousemcp:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: dollhousemcp:latest
    container_name: dollhousemcp
    # MCP servers are stdio-based and exit after initialization (expected behavior)
    restart: "no"
    environment:
      - NODE_ENV=production
      - PERSONAS_DIR=/app/personas
    volumes:
      # Mount custom personas directory (optional)
      - ./custom-personas:/app/custom-personas:ro
    # Network mode for MCP communication
    network_mode: "host"
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    # No health check needed for stdio-based MCP servers
    # MCP servers initialize, load personas, and exit (expected behavior)

  # Development service
  dollhousemcp-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: dollhousemcp:dev
    container_name: dollhousemcp-dev
    environment:
      - NODE_ENV=development
      - PERSONAS_DIR=/app/personas
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    profiles: ["dev"]