#!/bin/bash
# Setup script for self-hosted GitHub Actions runner
#
# Usage:
#   ./setup-runner.sh              # Setup and start macOS runner only
#   ./setup-runner.sh --linux      # Setup and start both macOS and Linux runners
#   ./setup-runner.sh --stop       # Stop all runners
#   ./setup-runner.sh --status     # Check runner status
#   ./setup-runner.sh --token      # Generate a new runner token

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check prerequisites
check_prereqs() {
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker Desktop first."
        exit 1
    fi

    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running. Please start Docker Desktop."
        exit 1
    fi

    if ! command -v gh &> /dev/null; then
        log_error "GitHub CLI (gh) is not installed. Install with: brew install gh"
        exit 1
    fi

    if ! gh auth status &> /dev/null; then
        log_error "GitHub CLI is not authenticated. Run: gh auth login"
        exit 1
    fi

    log_info "Prerequisites check passed"
}

# Get GitHub token (PAT with repo scope)
get_github_token() {
    # Try to get token from gh CLI
    TOKEN=$(gh auth token 2>/dev/null)

    if [ -z "$TOKEN" ]; then
        log_error "Could not get GitHub token. Make sure 'gh auth login' is configured."
        exit 1
    fi

    # Verify token has repo scope
    SCOPES=$(gh auth status 2>&1 | grep "Token scopes" || echo "")
    if [[ ! "$SCOPES" == *"repo"* ]]; then
        log_warn "Token may not have 'repo' scope. Runner registration might fail."
    fi

    echo "$TOKEN"
}

# Setup .env file
setup_env() {
    if [ -f .env ]; then
        log_warn ".env file already exists"
        read -p "Update token from gh CLI? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            return
        fi
    fi

    TOKEN=$(get_github_token)

    cat > .env << EOF
# Generated by setup-runner.sh on $(date)
# Using token from: gh auth token
GITHUB_TOKEN=$TOKEN
RUNNER_NAME=dollhouse-mac-runner
EOF

    log_info "Created .env file with gh auth token"
}

# Start runners
start_runners() {
    local profile=""
    if [ "$1" == "--linux" ]; then
        profile="--profile linux"
        log_info "Starting macOS and Linux runners..."
    else
        log_info "Starting macOS runner..."
    fi

    docker-compose $profile up -d

    log_info "Runner(s) started. Checking status..."
    sleep 3
    docker-compose ps

    echo ""
    log_info "View logs with: docker-compose logs -f"
    log_info "Check GitHub UI: https://github.com/DollhouseMCP/mcp-server-v2-refactor/settings/actions/runners"
}

# Stop runners
stop_runners() {
    log_info "Stopping all runners..."
    docker-compose --profile linux down
    log_info "Runners stopped"
}

# Show status
show_status() {
    log_info "Local container status:"
    docker-compose ps

    echo ""
    log_info "GitHub runner status:"
    gh api repos/DollhouseMCP/mcp-server-v2-refactor/actions/runners --jq '.runners[] | "  \(.name): \(.status) (labels: \([.labels[].name] | join(", ")))"' 2>/dev/null || echo "  No runners registered or unable to fetch"
}

# Main
case "${1:-}" in
    --token)
        check_prereqs
        TOKEN=$(get_github_token)
        echo ""
        log_info "GitHub token from gh CLI:"
        echo "${TOKEN:0:10}...${TOKEN: -4}"
        ;;
    --stop)
        stop_runners
        ;;
    --status)
        show_status
        ;;
    --linux)
        check_prereqs
        setup_env
        start_runners --linux
        ;;
    --help|-h)
        echo "Usage: $0 [option]"
        echo ""
        echo "Options:"
        echo "  (none)      Setup and start macOS runner"
        echo "  --linux     Setup and start both macOS and Linux runners"
        echo "  --stop      Stop all runners"
        echo "  --status    Check runner status"
        echo "  --token     Generate a new runner token"
        echo "  --help      Show this help"
        ;;
    *)
        check_prereqs
        setup_env
        start_runners
        ;;
esac
