/**
 * Centralized error codes for consistent error handling across the application.
 * Error codes follow the pattern: CATEGORY_SPECIFIC_ERROR
 */

/**
 * Validation error codes - Input validation failures
 */
export const ValidationErrorCodes = {
  // General validation
  INVALID_INPUT: 'VALIDATION_INVALID_INPUT',
  REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  INVALID_LENGTH: 'VALIDATION_INVALID_LENGTH',
  INVALID_RANGE: 'VALIDATION_INVALID_RANGE',
  INVALID_TYPE: 'VALIDATION_INVALID_TYPE',
  
  // Specific validation
  INVALID_PERSONA_ID: 'VALIDATION_INVALID_PERSONA_ID',
  INVALID_SEARCH_QUERY: 'VALIDATION_INVALID_SEARCH_QUERY',
  INVALID_COLLECTION_PATH: 'VALIDATION_INVALID_COLLECTION_PATH',
  INVALID_URL: 'VALIDATION_INVALID_URL',
  INVALID_FILENAME: 'VALIDATION_INVALID_FILENAME',
  INVALID_PATH: 'VALIDATION_INVALID_PATH',
  PATH_TRAVERSAL: 'VALIDATION_PATH_TRAVERSAL',
  INVALID_CHARACTER: 'VALIDATION_INVALID_CHARACTER',
  CONFIRMATION_REQUIRED: 'VALIDATION_CONFIRMATION_REQUIRED',
  INVALID_CATEGORY: 'VALIDATION_INVALID_CATEGORY',
  CONTENT_TOO_LARGE: 'VALIDATION_CONTENT_TOO_LARGE',
  
  // Template validation
  TEMPLATE_TOO_LARGE: 'VALIDATION_TEMPLATE_TOO_LARGE',
  TOO_MANY_VARIABLES: 'VALIDATION_TOO_MANY_VARIABLES',
  INVALID_INCLUDE_PATH: 'VALIDATION_INVALID_INCLUDE_PATH',
  MAX_INCLUDE_DEPTH: 'VALIDATION_MAX_INCLUDE_DEPTH',
  REQUIRED_VARIABLE: 'VALIDATION_REQUIRED_VARIABLE',
  DANGEROUS_PATTERN: 'VALIDATION_DANGEROUS_PATTERN',
  PATTERN_TOO_COMPLEX: 'VALIDATION_PATTERN_TOO_COMPLEX',
  PATTERN_MISMATCH: 'VALIDATION_PATTERN_MISMATCH',
  INVALID_PATTERN: 'VALIDATION_INVALID_PATTERN',
  INVALID_OPTIONS: 'VALIDATION_INVALID_OPTIONS',
  INVALID_NUMBER: 'VALIDATION_INVALID_NUMBER',
  INVALID_DATE: 'VALIDATION_INVALID_DATE',
  INVALID_ARRAY: 'VALIDATION_INVALID_ARRAY',
  INVALID_OBJECT: 'VALIDATION_INVALID_OBJECT',
  
  // Agent validation
  INVALID_FRAMEWORK: 'VALIDATION_INVALID_FRAMEWORK',
  INVALID_RISK_TOLERANCE: 'VALIDATION_INVALID_RISK_TOLERANCE',
  MAX_GOALS_EXCEEDED: 'VALIDATION_MAX_GOALS_EXCEEDED',
  GOAL_TOO_SHORT: 'VALIDATION_GOAL_TOO_SHORT',
  HARMFUL_CONTENT: 'VALIDATION_HARMFUL_CONTENT',
  DEPENDENCY_CYCLE: 'VALIDATION_DEPENDENCY_CYCLE',
  GOAL_NOT_FOUND: 'VALIDATION_GOAL_NOT_FOUND',
  INVALID_GOAL_STATUS: 'VALIDATION_INVALID_GOAL_STATUS',
  CONTEXT_TOO_LARGE: 'VALIDATION_CONTEXT_TOO_LARGE',
  STATE_TOO_LARGE: 'VALIDATION_STATE_TOO_LARGE',
} as const;

/**
 * Network error codes - API and network failures
 */
export const NetworkErrorCodes = {
  REQUEST_FAILED: 'NETWORK_REQUEST_FAILED',
  INVALID_RESPONSE: 'NETWORK_INVALID_RESPONSE',
  RESPONSE_TOO_LARGE: 'NETWORK_RESPONSE_TOO_LARGE',
  API_ERROR: 'NETWORK_API_ERROR',
  RATE_LIMIT_EXCEEDED: 'NETWORK_RATE_LIMIT_EXCEEDED',
  FETCH_FAILED: 'NETWORK_FETCH_FAILED',
} as const;

/**
 * System error codes - Internal system failures
 */
export const SystemErrorCodes = {
  LOAD_FAILED: 'SYSTEM_LOAD_FAILED',
  SAVE_FAILED: 'SYSTEM_SAVE_FAILED',
  DELETE_FAILED: 'SYSTEM_DELETE_FAILED',
  IMPORT_FAILED: 'SYSTEM_IMPORT_FAILED',
  EXPORT_FAILED: 'SYSTEM_EXPORT_FAILED',
  DESERIALIZATION_FAILED: 'SYSTEM_DESERIALIZATION_FAILED',
  UNKNOWN_FRAMEWORK: 'SYSTEM_UNKNOWN_FRAMEWORK',
  UNSUPPORTED_FORMAT: 'SYSTEM_UNSUPPORTED_FORMAT',
} as const;

/**
 * All error codes combined for easy access
 */
export const ErrorCodes = {
  ...ValidationErrorCodes,
  ...NetworkErrorCodes,
  ...SystemErrorCodes,
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];