export {
  AUTO_REPAIRABLE_HOOK_HOSTS,
  MANAGED_HOOK_WRAPPER_BASENAMES,
  WRAPPER_HOOK_HOSTS,
  type HookAssetAuditResult,
  type HookAssetDescriptor,
  type InstallPermissionHookOptions,
  type InstallPermissionHookResult,
  type PermissionHookAuditSummary,
  type PermissionHookDiagnosticRecord,
  type PermissionHookHealthSummary,
  type PermissionHookMarker,
  type PermissionHookStartupRepairHostResult,
  type PermissionHookStartupRepairSummary,
  type PermissionHookStatus,
  type ReconcilePermissionHookOptions,
  detectIndent,
  getClaudeHookSettingsPath,
  getCodexConfigPath,
  getPermissionHookDiagnosticsPath,
  getCodexHookSettingsPath,
  getCursorHookSettingsPath,
  getGeminiHookSettingsPath,
  getHookSourcePath,
  getHookWrapperBasename,
  getHookWrapperPath,
  getManagedHookAssets,
  getPermissionHookMarkerPath,
  getPermissionHookScriptPath,
  getPrimaryHookScriptPath,
  getVsCodeHookSettingsPath,
  getVsCodeUserSettingsPath,
  getWindsurfHookSettingsPath,
  installHookAssetsForHost,
  isMissingFileError,
  normalizeHookHost,
  readLastPermissionHookDiagnostic,
  readOptionalUtf8,
  supportsManagedHookAssets,
  writeBackupIfPresent,
} from './permissionHookShared.js';

export {
  ensureClaudePreToolUseHook,
  ensureCodexPreToolUseHook,
  ensureCursorPreToolUseHook,
  ensureGeminiBeforeToolHook,
  ensureVsCodePreToolUseHook,
  ensureWindsurfHooks,
  installPermissionHook,
} from './permissionHookInstallers.js';

export {
  _resetPermissionHookStartupRepairSummaryForTests,
  getLastPermissionHookStartupRepairSummary,
  getPermissionHookAuditSummary,
  getPermissionHookStatus,
  getPermissionHookStatusAsync,
  reconcilePermissionHookStatus,
  repairPermissionHooksOnStartup,
  summarizePermissionHookHealth,
} from './permissionHookStatus.js';
