name: Claude Code Review

# Automated PR Review Workflow
# =============================
# AUTOMATIC TRIGGERING: This workflow runs automatically on:
#   - New pull requests (opened) from authorized users only
#   - Updated pull requests (synchronize) from authorized users only
#
# SECURITY MODEL:
#   - Only runs for PRs created by explicitly authorized users
#   - Currently authorized: mickdarling (repository owner)
#   - Add new users by updating the conditional logic below
#
# PERMISSIONS: 
#   - Read-only access to repository content
#   - Write access to post review comments
#   - Cannot modify repository files (review-only)
#
# SECURITY NOTES:
#   - Restricted to authorized users only (not all contributors)
#   - Uses read-only permissions for safety
#   - All reviews are logged in GitHub Actions history
#   - Unauthorized PRs will not trigger automated review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes (uncomment when repo grows)
    # Saves GitHub Actions minutes and API calls for irrelevant changes
    # paths:
    #   - "src/**/*.ts"           # TypeScript source files
    #   - "src/**/*.tsx"          # TypeScript React files
    #   - "src/**/*.js"           # JavaScript files
    #   - "src/**/*.jsx"          # JavaScript React files
    #   - "*.md"                  # Documentation files
    #   - "package.json"          # Dependencies
    #   - "tsconfig.json"         # TypeScript config
    #   - ".github/workflows/**"  # Workflow files themselves
    # paths-ignore:
    #   - "dist/**"               # Ignore compiled output
    #   - "node_modules/**"       # Ignore dependencies
    #   - "coverage/**"           # Ignore test coverage

jobs:
  claude-review:
    # Security: Only run automated reviews for authorized users
    if: |
      github.event.pull_request.user.login == 'mickdarling' ||
      github.actor == 'mickdarling'
      # Add new authorized users here: || github.event.pull_request.user.login == 'username'
    
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read           # Read-only: this workflow only reviews, doesn't modify
      pull-requests: write     # Write needed: to post review comments
      issues: read             # Read-only: just needs to read issue context
      id-token: write          # Write needed: for OIDC authentication
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Full git history for comprehensive review context
          # TODO: Consider fetch-depth: 50-100 when repo reaches 500+ commits
          fetch-depth: 0

      - name: Validate Workflow YAML
        run: |
          # Check if any workflow files were modified and validate them
          changed_workflows=$(git diff --name-only HEAD~1 HEAD -- .github/workflows/ || echo "")
          if [ -n "$changed_workflows" ]; then
            echo "Validating modified workflow files..."
            for file in $changed_workflows; do
              if [ -f "$file" ]; then
                echo "Validating $file"
                python -c "import yaml; yaml.safe_load(open('$file'))" || {
                  echo "❌ YAML syntax error in $file"
                  exit 1
                }
                echo "✅ $file is valid YAML"
              fi
            done
          else
            echo "No workflow files modified, skipping validation"
          fi

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v0.0.27
        continue-on-error: true
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            
            Be constructive and helpful in your feedback.
          
          # Optional: Customize review based on file types
          # direct_prompt: |
          #   Review this PR focusing on:
          #   - For TypeScript files: Type safety and proper interface usage
          #   - For API endpoints: Security, input validation, and error handling
          #   - For React components: Performance, accessibility, and best practices
          #   - For tests: Coverage, edge cases, and test quality
          
          # Optional: Different prompts for different authors
          # direct_prompt: |
          #   ${{ github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' && 
          #   'Welcome! Please review this PR from a first-time contributor. Be encouraging and provide detailed explanations for any suggestions.' ||
          #   'Please provide a thorough code review focusing on our coding standards and best practices.' }}
          
          # Optional: Add specific tools for running tests or linting
          # allowed_tools: "Bash(npm run test),Bash(npm run lint),Bash(npm run typecheck)"
          
          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')

      - name: Handle Claude API Failure
        if: steps.claude-review.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Claude Code Review temporarily unavailable**\n\nThe Claude API appears to be experiencing issues. The automated review could not be completed. Please try again later or request manual review if needed.'
            });

