---
name: Core Build & Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  NODE_OPTIONS: --max-old-space-size=4096
  CI: true

jobs:
  core-test:
    name: Test (${{ matrix.os }}, Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['20.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Temporarily disabled TypeScript cache to debug CI issues
      # - name: Cache TypeScript build
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       dist/
      #       build/
      #       *.tsbuildinfo
      #     key: typescript-build-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('src/**/*.ts', 'tsconfig*.json', 'package.json', 'package-lock.json') }}
      #     restore-keys: |
      #       typescript-build-${{ runner.os }}-${{ matrix.node-version }}-
      #       typescript-build-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Debug file structure
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Node version ==="
          node --version
          echo "=== NPM version ==="
          npm --version
          echo "=== Root files ==="
          ls -la jest.* || echo "No jest files found"
          echo "=== Source files ==="
          ls -la src/update/ || echo "src/update not found"
          echo "=== Config files ==="
          ls -la src/config/ || echo "src/config not found"
          echo "=== Dist files ==="
          ls -la dist/update/ || echo "dist/update not found"
          echo "=== Test files ==="
          ls -la __tests__/unit/auto-update/ || echo "auto-update tests not found"
          echo "=== NODE_PATH ==="
          echo $NODE_PATH
          echo "=== Jest config ==="
          cat jest.config.cjs

      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: |
            .jest-cache/
            coverage/
            node_modules/.cache/jest/
          key: jest-cache-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('__tests__/**/*.ts', 'jest.config.*', 'src/**/*.ts', 'package.json', 'package-lock.json') }}
          restore-keys: |
            jest-cache-${{ runner.os }}-${{ matrix.node-version }}-
            jest-cache-${{ runner.os }}-

      - name: Run test suite
        run: npm test

      - name: Validation complete
        run: |
          echo "✅ Core Build & Test Complete!"
          echo "Platform: ${{ matrix.os }}"
          echo "Node.js: ${{ matrix.node-version }}"