name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.2.3
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  packages: write

jobs:
  publish-gpr:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@DollhouseMCP'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure package.json for GitHub Packages
        run: |
          # Create a temporary package.json for GitHub Packages
          # GitHub Packages requires the package name to match the org/repo format
          node -e "
          const pkg = require('./package.json');
          pkg.name = '@DollhouseMCP/mcp-server';
          pkg.publishConfig = {
            registry: 'https://npm.pkg.github.com'
          };
          require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          console.log('Updated package name for GitHub Packages: ' + pkg.name);
          "

      - name: Check if version already published
        id: check_version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "Checking if version $PACKAGE_VERSION is already published..."

          # Try to fetch package info from GitHub Packages
          # Use npm view with the GitHub Packages registry
          if npm view @DollhouseMCP/mcp-server@$PACKAGE_VERSION --registry=https://npm.pkg.github.com version 2>/dev/null; then
            echo "Version $PACKAGE_VERSION already exists on GitHub Packages"
            echo "already_published=true" >> $GITHUB_OUTPUT
          else
            echo "Version $PACKAGE_VERSION not found, proceeding with publication"
            echo "already_published=false" >> $GITHUB_OUTPUT
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        if: steps.check_version.outputs.already_published == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Skip publication (already exists)
        if: steps.check_version.outputs.already_published == 'true'
        run: |
          echo "⏭️ Skipping publication - version already exists on GitHub Packages"
          echo "This is expected if the tag was re-pushed or if multiple commits reference the same tag"

      - name: Restore original package.json
        if: always()
        run: |
          git checkout -- package.json

      - name: Notify success
        if: success()
        run: |
          if [ "${{ steps.check_version.outputs.already_published }}" == "true" ]; then
            echo "✅ Workflow completed successfully (publication skipped - version already exists)"
          else
            echo "✅ Successfully published to GitHub Packages!"
            echo "📦 Package will appear in the repository's Packages section"
          fi