name: Test Docker Auth

on:
  workflow_dispatch:

jobs:
  test-docker-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Test Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test Pull Alpine
        run: |
          echo "✅ Docker login successful!"
          docker pull alpine:latest
          echo "✅ Successfully pulled alpine:latest"